import type { Admin, LogbookEntry, Mentor, Peserta } from "./types";

export const DEMO_PASSWORD = "magang123";
export const DEMO_GOOGLE_EMAIL = "peserta.demo@gmail.com";

export const MOCK_ADMINS: Admin[] = [
  {
    nama: "Admin ATR/BPN",
    email: "admin@atrbpn.go.id",
    password: DEMO_PASSWORD,
  },
];

export const DIVISI_LIST = [
  "Survei & Pemetaan",
  "Hak Tanah & Pendaftaran",
  "Penataan Agraria",
  "Pengendalian & Penanganan Sengketa",
  "Tata Usaha",
] as const;

export const MOCK_PESERTA: Peserta[] = [
  {
    id: "p1",
    nama: "Ayu Lestari",
    email: "ayu.lestari@student.ac.id",
    password: DEMO_PASSWORD,
    asalInstansi: "Universitas Gadjah Mada",
    jurusan: "Ilmu Hukum",
    jenjang: "Mahasiswa",
    divisi: "Hak Tanah & Pendaftaran",
    mentorNama: "Budi Santoso",
    periodeMulai: "2026-07-01",
    periodeSelesai: "2026-09-30",
    status: "aktif",
    akunStatus: "disetujui",
  },
  {
    id: "p2",
    nama: "Rafi Ramadhan",
    email: "rafi.ramadhan@student.ac.id",
    password: DEMO_PASSWORD,
    asalInstansi: "Politeknik STPN Yogyakarta",
    jurusan: "Teknik Geodesi",
    jenjang: "Mahasiswa",
    divisi: "Survei & Pemetaan",
    mentorNama: "Siti Nurhaliza",
    periodeMulai: "2026-08-01",
    periodeSelesai: "2026-11-30",
    status: "aktif",
    akunStatus: "disetujui",
  },
  {
    id: "p3",
    nama: "Dewi Anggraini",
    email: "dewi.anggraini@smkn.sch.id",
    password: DEMO_PASSWORD,
    asalInstansi: "SMKN 1 Purwokerto",
    jurusan: "Otomatisasi Tata Kelola Perkantoran",
    jenjang: "SMK/SMA",
    divisi: "Tata Usaha",
    mentorNama: "Budi Santoso",
    periodeMulai: "2026-06-15",
    periodeSelesai: "2026-09-15",
    status: "aktif",
    akunStatus: "disetujui",
  },
  {
    id: "p4",
    nama: "Fajar Nugroho",
    email: "fajar.nugroho@student.ac.id",
    password: DEMO_PASSWORD,
    asalInstansi: "Universitas Diponegoro",
    jurusan: "Perencanaan Wilayah & Kota",
    jenjang: "Mahasiswa",
    divisi: "Penataan Agraria",
    mentorNama: "Siti Nurhaliza",
    periodeMulai: "2026-07-15",
    periodeSelesai: "2026-10-15",
    status: "aktif",
    akunStatus: "disetujui",
  },
  {
    id: "p5",
    nama: "Putri Wulandari",
    email: "putri.wulandari@student.ac.id",
    password: DEMO_PASSWORD,
    asalInstansi: "Universitas Jenderal Soedirman",
    jurusan: "Ilmu Hukum",
    jenjang: "Mahasiswa",
    divisi: "Pengendalian & Penanganan Sengketa",
    mentorNama: "Budi Santoso",
    periodeMulai: "2026-03-01",
    periodeSelesai: "2026-06-01",
    status: "selesai",
    akunStatus: "disetujui",
  },
  {
    id: "p-google-demo",
    nama: "Peserta Demo Google",
    email: DEMO_GOOGLE_EMAIL,
    password: "google-oauth-demo",
    asalInstansi: "Universitas Demo",
    jurusan: "Sistem Informasi",
    jenjang: "Mahasiswa",
    divisi: "Menunggu Penempatan",
    mentorNama: "Belum ditentukan",
    periodeMulai: "2026-09-01",
    periodeSelesai: "2026-12-01",
    status: "aktif",
    akunStatus: "disetujui",
  },
  {
    id: "p-pending-1",
    nama: "Naufal Hakim",
    email: "naufal.hakim@student.ac.id",
    password: DEMO_PASSWORD,
    asalInstansi: "Universitas Brawijaya",
    jurusan: "Teknik Geodesi",
    jenjang: "Mahasiswa",
    divisi: "Menunggu Penempatan",
    mentorNama: "Belum ditentukan",
    periodeMulai: "2026-09-18",
    periodeSelesai: "2026-09-18",
    status: "aktif",
    akunStatus: "pending",
  },
  {
    id: "p-pending-2",
    nama: "Salsabila Rahma",
    email: "salsabila.rahma@smkn.sch.id",
    password: DEMO_PASSWORD,
    asalInstansi: "SMKN 2 Yogyakarta",
    jurusan: "Otomatisasi Tata Kelola Perkantoran",
    jenjang: "SMK/SMA",
    divisi: "Menunggu Penempatan",
    mentorNama: "Belum ditentukan",
    periodeMulai: "2026-09-17",
    periodeSelesai: "2026-09-17",
    status: "aktif",
    akunStatus: "pending",
  },
];

export const MOCK_MENTORS: Mentor[] = [
  {
    id: "m1",
    nama: "Budi Santoso",
    email: "budi.santoso@atrbpn.go.id",
    password: DEMO_PASSWORD,
    nip: "196801011990031001",
    akunStatus: "disetujui",
  },
  {
    id: "m2",
    nama: "Siti Nurhaliza",
    email: "siti.nurhaliza@atrbpn.go.id",
    password: DEMO_PASSWORD,
    nip: "197505152000032002",
    akunStatus: "disetujui",
  },
  {
    id: "m-pending-1",
    nama: "Arif Wibowo",
    email: "arif.wibowo@atrbpn.go.id",
    password: DEMO_PASSWORD,
    nip: "198903102015031004",
    akunStatus: "pending",
  },
];

export const MOCK_LOGBOOK: LogbookEntry[] = [
  {
    id: "lb1",
    pesertaId: "p1",
    pesertaNama: "Ayu Lestari",
    divisi: "Hak Tanah & Pendaftaran",
    tanggal: "2026-09-01",
    jamMulai: "08:00",
    jamSelesai: "16:00",
    aktivitas: "Membantu verifikasi berkas permohonan sertipikat tanah masuk.",
    output: "30 berkas permohonan terverifikasi kelengkapannya.",
    status: "verified",
    catatanMentor: "Kerja rapi, lanjutkan pemeriksaan berkas batch berikutnya.",
    diverifikasiOleh: "Budi Santoso",
    diperbaruiPada: "2026-09-01T17:10:00",
  },
  {
    id: "lb2",
    pesertaId: "p2",
    pesertaNama: "Rafi Ramadhan",
    divisi: "Survei & Pemetaan",
    tanggal: "2026-09-01",
    jamMulai: "08:00",
    jamSelesai: "15:30",
    aktivitas: "Ikut pengukuran bidang tanah menggunakan GPS geodetik di lapangan.",
    output: "Data koordinat 8 bidang tanah terekam untuk diproses.",
    status: "pending",
    diperbaruiPada: "2026-09-01T16:00:00",
  },
  {
    id: "lb3",
    pesertaId: "p3",
    pesertaNama: "Dewi Anggraini",
    divisi: "Tata Usaha",
    tanggal: "2026-09-01",
    jamMulai: "08:00",
    jamSelesai: "14:00",
    aktivitas: "Input surat masuk dan keluar ke sistem persuratan elektronik.",
    output: "45 surat terdata dan terdistribusi ke unit terkait.",
    status: "pending",
    diperbaruiPada: "2026-09-01T14:20:00",
  },
  {
    id: "lb4",
    pesertaId: "p4",
    pesertaNama: "Fajar Nugroho",
    divisi: "Penataan Agraria",
    tanggal: "2026-08-31",
    jamMulai: "08:00",
    jamSelesai: "16:00",
    aktivitas: "Menyusun draf peta penggunaan tanah untuk kajian redistribusi.",
    output: "Draf peta tematik versi 1 selesai dan siap direview.",
    status: "revisi",
    catatanMentor: "Legenda peta perlu ditambahkan, tolong lengkapi kembali.",
    diverifikasiOleh: "Siti Nurhaliza",
    diperbaruiPada: "2026-08-31T17:45:00",
  },
  {
    id: "lb5",
    pesertaId: "p1",
    pesertaNama: "Ayu Lestari",
    divisi: "Hak Tanah & Pendaftaran",
    tanggal: "2026-08-31",
    jamMulai: "08:00",
    jamSelesai: "16:00",
    aktivitas: "Mendampingi loket pelayanan pendaftaran tanah pertama kali.",
    output: "Mencatat 12 permohonan baru beserta kelengkapan dokumennya.",
    status: "verified",
    catatanMentor: "Baik, komunikasi dengan pemohon sudah cukup jelas.",
    diverifikasiOleh: "Budi Santoso",
    diperbaruiPada: "2026-08-31T17:00:00",
  },
];
